version: "3.7"

services:
       axelar-core:
            image: axelarnet/axelar-core:${AXELAR_CORE_VERSION}
            container_name: axelar-core
            ports:
               - 1317:1317
               - 26656-26658:26656-26658
               - 26660:26660
            environment:
               - TOFND_HOST=host.docker.internal
               - START_REST=true
               - PEERS_FILE=/root/shared/peers.txt
               - INIT_SCRIPT=/root/shared/consumeGenesis.sh
               - CONFIG_PATH=/root/shared/
               - ROOT_DIRECTORY=/home/ubuntu
               - SHARED_DIRECTORY=/home/ubuntu
               - AXELAR_CORE_VERSION=v0.4.3
            volumes:
               - ${ROOT_DIRECTORY}/.axelar:/root/.axelar
               - ${SARED_DIRECTORY}:/root/shared
       tofnd:
            image: axelarnet/tofnd:${TOFND_VERSION}
            container_name: tofnd
            environment:
                - ROOT_DIRECTORY=/home/ubuntu
                - TOFND_VERSION=v0.3.0
            ports:
                - 50051:50051
            volumes:
                - ${ROOT_DIRECTORY}:/root/.kvstoreH
